### PR TITLE
Hugectr inference multihot example

### PR DESCRIPTION
**Pull request by albert17**
Initial inference notebook from #1021 
Previous existing reference #1144 

Removes single hot example

### CODE REVIEW

**Comment by albert17** [comment]
@rnyak @jershi425
Currently getting an error in training notebook
```
=====================================================Model Fit=====================================================
[HUGECTR][20:42:43][INFO][RANK0]: Use non-epoch mode with number of iterations: 2000
[HUGECTR][20:42:43][INFO][RANK0]: Training batchsize: 2048, evaluation batchsize: 2048
[HUGECTR][20:42:43][INFO][RANK0]: Evaluation interval: 200, snapshot interval: 1900
[HUGECTR][20:42:43][INFO][RANK0]: Sparse embedding trainable: 1, dense network trainable: 1
[HUGECTR][20:42:43][INFO][RANK0]: Use mixed precision: 0, scaler: 1, use cuda graph: -891441590
[HUGECTR][20:42:43][INFO][RANK0]: lr: 0.001000, warmup_steps: 1, decay_start: 0, decay_steps: 1, decay_power: 2.000000, end_lr: 0.000000
[HUGECTR][20:42:43][INFO][RANK0]: Training source file: /root/nvt-examples/movielens/data/train/_file_list.txt
[HUGECTR][20:42:43][INFO][RANK0]: Evaluation source file: /root/nvt-examples/movielens/data/valid/_file_list.txt
terminate called after throwing an instance of 'HugeCTR::internal_runtime_error'
  what():  Runtime error: an illegal memory access was encountered /var/tmp/HugeCTR/HugeCTR/src/embeddings/localized_slot_sparse_embedding_hash.cu:141 

[a2eb792b60ca:00602] *** Process received signal ***
[a2eb792b60ca:00602] Signal: Aborted (6)
[a2eb792b60ca:00602] Signal code:  (-6)
Runtime error: an illegal memory access was encountered /var/tmp/HugeCTR/HugeCTR/src/data_readers/parquet_data_converter.cu:404 

[a2eb792b60ca:00602] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f05cd915210]
[a2eb792b60ca:00602] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f05cd91518b]
[a2eb792b60ca:00602] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f05cd8f4859]
[a2eb792b60ca:00602] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911)[0x7f05b376e911]
[a2eb792b60ca:00602] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7f05b377a38c]
[a2eb792b60ca:00602] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa9369)[0x7f05b3779369]
[a2eb792b60ca:00602] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x2a1)[0x7f05b3779d21]
[a2eb792b60ca:00602] [ 7] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(+0x10bef)[0x7f05b3683bef]
[a2eb792b60ca:00602] [ 8] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume+0x12a)[0x7f05b36845aa]
[a2eb792b60ca:00602] [ 9] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR32LocalizedSlotSparseEmbeddingHashIxfE19filter_keys_per_gpuEbmmm+0xb94)[0x7f05ca9c0144]
[a2eb792b60ca:00602] [10] /usr/local/hugectr/lib/libhuge_ctr_shared.so(+0x5946a2)[0x7f05ca9c06a2]
[a2eb792b60ca:00602] [11] /usr/lib/x86_64-linux-gnu/libgomp.so.1(GOMP_parallel+0x46)[0x7f05b36a08e6]
[a2eb792b60ca:00602] [12] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR32LocalizedSlotSparseEmbeddingHashIxfE7forwardEbi+0x5a)[0x7f05ca9c084a]
[a2eb792b60ca:00602] [13] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR5Model5trainEv+0x2a3)[0x7f05cadce253]
[a2eb792b60ca:00602] [14] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR5Model3fitEiiiiiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xd16)[0x7f05caddb976]
[a2eb792b60ca:00602] [15] /usr/local/hugectr/lib/hugectr.so(+0xd0543)[0x7f05cd331543]
[a2eb792b60ca:00602] [16] /usr/local/hugectr/lib/hugectr.so(+0xcc498)[0x7f05cd32d498]
[a2eb792b60ca:00602] [17] python(PyCFunction_Call+0x59)[0x5f5db9]
[a2eb792b60ca:00602] [18] python(_PyObject_MakeTpCall+0x29e)[0x5f698e]
[a2eb792b60ca:00602] [19] python[0x50b4c7]
[a2eb792b60ca:00602] [20] python(_PyEval_EvalFrameDefault+0x186a)[0x56cf2a]
[a2eb792b60ca:00602] [21] python(_PyEval_EvalCodeWithName+0x26a)[0x56a0ba]
[a2eb792b60ca:00602] [22] python(PyEval_EvalCode+0x27)[0x68d5b7]
[a2eb792b60ca:00602] [23] python[0x67cd01]
[a2eb792b60ca:00602] [24] python[0x67cd7f]
[a2eb792b60ca:00602] [25] python[0x67ce21]
[a2eb792b60ca:00602] [26] python(PyRun_SimpleFileExFlags+0x197)[0x67ef47]
[a2eb792b60ca:00602] [27] python(Py_RunMain+0x212)[0x6b7242]
[a2eb792b60ca:00602] [28] python(Py_BytesMain+0x2d)[0x6b75cd]
[a2eb792b60ca:00602] [29] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f05cd8f60b3]
[a2eb792b60ca:00602] *** End of error message ***
Aborted (core dumped)
```

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
@benfred @gabrielspmoreira

Actually installing numpy before tf4rec does not work, because tf4rec downgrades it.

So I guess we can 1) Add the numpy install in the script as Gabriel proposed; 2) I can edit the script on the CI side to add the numpy install.

I prefer option 1) as Gabriel suggested.

**Comment by bschifferer** [comment]
I got more feedback from our SAs to update some of the wording in the movielens notebook. Please notify me, when the notebooks are final and I make an update to the text.

**Comment by albert17** [comment]
Fixed HugeCTR training error thanks to @jershi425. Setting `nnz_per_slot=10`

**Comment by albert17** [comment]
@jershi425 I just started to get the error `Illegal instruction (core dumped)` when running training in HugeCTR.

Has there been any update in HugeCTR I am not aware?
@jershi425 Please, update this PR as considered

**Comment by albert17** [comment]
Closing in favor of #1329

**Pull request closed without merging**
