### PR TITLE
Update imports for classes that moved to `merlin-core`

### PR DESCRIPTION
**Pull request by karlhigley**

### CODE REVIEW

**Comment by karlhigley** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Review by jperez999 — APPROVED** [review]

**Pull request merged**
