### PR TITLE
add init file for import support

### PR DESCRIPTION
**Pull request by jperez999**

### CODE REVIEW

**Comment by jperez999** [comment]
test is already in there if you look here: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/tests/unit/graph/test_column_schemas.py#L22

**Review by karlhigley — APPROVED** [review]

**Review by benfred — APPROVED** [review]

**Comment by albert17** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Pull request merged**
