### PR TITLE
remove horovod example, no longer supported

### PR DESCRIPTION
**Pull request by jperez999**
we already have torch distributed example!

### CODE REVIEW

**Comment by karlhigley** [comment]
I think there's also a notebook that should be removed?

**Comment by mikemckiernan** [comment]
It's cool by me to remove the notebook if it no longer applies.  I'm chiming in because I planned to make that notebook public in the doc:

<https://nvidia-merlin.github.io/NVTabular/review/pr-1529/examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.html?highlight=torch_trainer#>

Please send me a signal to confirm that we want to remove the notebook.

**Comment by karlhigley** [comment]
@mikemckiernan Yeah, the notebook has to go, since we're dropping support for the PyTorch/Horovod combo and removing Horovod from the Torch containers. Doesn't matter to me which PR it gets removed in as long as it disappears somehow.

**Comment by bschifferer** [comment]
@jperez999 where is the "torch distributed example"? Do we know if there are performance differences between using torch.distributed and horovod?

**Comment by bschifferer** [comment]
I think the notebook ( https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-PyTorch.ipynb ) generated torch_trainer.py. 

We need to remove the notebook, as well / update to generate `torch_trainer_dist.py` ?

**Comment by jperez999** [comment]
@bschifferer Sorry I don't know the diff off the top of my head. And I don't think my old perf runs are good for current comparison.

**Review by karlhigley — APPROVED** [review]

**Pull request merged**
