### PR TITLE
fixed lambdaop call

### LINKED ISSUE #1392: [BUG] NVTabular ETL multi-GPU breaks, if datatypes for column changes
**Describe the bug**
If I run the multi-GPU NVTabular ETL workflows, they throw errors, when datatype of a column changes.

Examples
Movielens: `Exception: "TypeError('Improperly matched output dtypes detected in rating, float64 and int8')"`
Criteo: `Exception: "TypeError('Improperly matched output dtypes detected in C1, int64 and int32')"`

**Steps/Code to reproduce bug**
Run multi-GPU Movielens: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/multi-gpu-movielens/01-03-MultiGPU-Download-Convert-ETL-with-NVTabular-Training-with-TensorFlow.ipynb
Run criteo: https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/02-ETL-with-NVTabular.ipynb 

**Environment details (please complete the following information):**
- merlin-tensorflow-training:22.02 with latest main branch 
 
**Additional information:**
- I tested single-GPU movielens and it worked.
- I changed the single-GPU movielens example to use multi-GPUs and then it breaks
- if I change `ratings = nvt.ColumnSelector(["rating"]) >> nvt.ops.LambdaOp(lambda col: (col > 3.0).astype("int8"))` to `ratings = nvt.ColumnSelector(["rating"])`, then multi-GPU movielens works as well

### PR DESCRIPTION
**Pull request by jperez999**
closes #1392

### CODE REVIEW

**Review by karlhigley — APPROVED** [review]

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Review by benfred — COMMENTED** [review]
I think this fixes the multigpu movielens notebook - but Benedikt was also reporting the criteo notebook failing with `Criteo: Exception: "TypeError('Improperly matched output dtypes detected in C1, int64 and int32')"`  in #1392
 
Did you manage to replicate that problem with Criteo ?

**Comment by jperez999** [comment]
The criteo issue stems from our current tensorflow metadata protobuf representation for data types. ( can only express the type and not the itemsize ...,32,64)

**Comment by jperez999** [comment]
for now we have to force an infer_schema step to verify the dtype (because of lack of itemsize support)

**Pull request merged**
