### PR TITLE
Describe how to check for broken links

### PR DESCRIPTION
**Pull request by mikemckiernan**
This is one way to check for broken links,
but I'm happy to adopt something that is
better.

### CODE REVIEW

**Comment by mikemckiernan** [comment]
Let's review and merge after https://github.com/NVIDIA-Merlin/NVTabular/pull/1711.  Several broken links are resolved in that PR.

**Comment by mikemckiernan** [comment]
rerun tests

**Review by karlhigley — APPROVED** [review]

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
rerun tests

**Comment by mikemckiernan** [comment]
I know that I suggested waiting until another PR was merged, but when Jenkins finally says you can merge, you really, really need to merge.

**Pull request merged**
