### PR TITLE
Add Multi-hot feature into the movie-lens example

### PR DESCRIPTION
**Pull request by jershi425**
Added 'genres' as a multi-hot feature into the sample.

### CODE REVIEW

**Comment by rnyak** [comment]
@jershi425 when I train the model in the `Training-with-HugeCTR` nb, I get the following during model training:

```
[22d23h55m60s][HUGECTR][INFO]: Iter: 1900 Time(100 iters): 0.262071s Loss: 0.523336 lr:0.001000
[22d23h55m60s][HUGECTR][INFO]: Rank0: Dump hash table from GPU0
[22d23h55m60s][HUGECTR][INFO]: Rank0: Write hash table <key,value> pairs to file
[22d23h55m60s][HUGECTR][INFO]: Done
[22d23h55m60s][HUGECTR][INFO]: Dumping sparse weights to files, successful
[22d23h55m60s][HUGECTR][INFO]: Rank0: Write optimzer state to file
[22d23h55m60s][HUGECTR][INFO]: Done
[22d23h55m60s][HUGECTR][INFO]: Rank0: Write optimzer state to file
[22d23h55m60s][HUGECTR][INFO]: Done
[22d23h55m60s][HUGECTR][INFO]: Dumping sparse optimzer states to files, successful
[22d23h55m60s][HUGECTR][INFO]: Dumping dense weights to file, successful
[22d23h55m60s][HUGECTR][INFO]: Dumping dense optimizer states to file, successful
[22d23h55m60s][HUGECTR][INFO]: Dumping untrainable weights to file, successful
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
Finish 2000 iterations with batchsize: 2048 in 5.82s
[22d23h55m70s][HUGECTR][INFO]: Save the model graph to /model/movielens_hugectr/1/movielens.json, successful
```
Do you have any idea why I am getting `set_mempolicy: Operation not permitted` ? I use `merlin-training:0.6` docker image.

**Comment by rnyak** [comment]
@jershi425 can you also explain these lines?  why `range(1, 31)` ? where is `31` coming from? thanks.

```
rp_lst = [0]
cur = 0
for i in range(1, 31):
    if i % 3 == 0:
        cur += 2
        rp_lst.append(cur)
    else:
        cur += 1
        rp_lst.append(cur)
```

**Comment by jershi425** [comment]
@rnyak The  `set_mempolicy: Operation not permitted` issue can be solved after you add `--privileged` when you start your docker container. The range(1, 31) comes from the fact that we have 3 columns in our data and I am using the first 10 samples to do the inference test. Therefore we have 3 * 10 = 30 row pointers.

**Comment by rnyak** [comment]
> @rnyak The `set_mempolicy: Operation not permitted` issue can be solved after you add `--privileged` when you start your docker container. The range(1, 31) comes from the fact that we have 3 columns in our data and I am using the first 10 samples to do the inference test. Therefore we have 3 * 10 = 30 row pointers.

@jershi425 thanks I solved `set_mempolicy` warning.  Thanks for the explanation regarding range(1, 31).

**Comment by albert17** [comment]
@rnyak @jershi425 what is the plan for this PR?

**Comment by rnyak** [comment]
> @rnyak @jershi425 what is the plan for this PR?

@albert17 we already have [multi-hot training example](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/03-Training-with-HugeCTR.ipynbhttps://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/03-Training-with-HugeCTR.ipynb) with HugeCTR based on this PR. It should work without issues.  What is missing the `inference` part. You only need to make the inference code created by Onur's PR and you can take Jerry's inference notebook as a guidance/reference/test point. Once you are done we can close this PR without merging :)

**Comment by albert17** [comment]
Awesome.

Then we don't need this notebooks? https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/inference-HugeCTR/Training-with-HugeCTR.ipynb

**Pull request closed without merging**
