### PR TITLE
Add a `compute_input_schema` method to operators

### PR DESCRIPTION
**Pull request by jperez999**
introduce method for graph operators to manipulate input schemas when necessary (like for operators representing workflow or TF model execution in Triton, which have fixed input schemas based on the workflow or model they contain)

### CODE REVIEW

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by karlhigley** [comment]
rerun tests

**Review by karlhigley — APPROVED** [review]

**Comment by karlhigley** [comment]
rerun tests

**Pull request merged**
