### PR TITLE
Normalize Op using fp32

### PR DESCRIPTION
**Pull request by benfred**
Normalize Op used fp64 and was not compatible with tensorflow.
I added out_dtypes as parameter to provide the user the option to use fp32 instead of fp64

using fp64 broke some unittests

### CODE REVIEW

**Comment by benfred** [comment]
This is a test to see if the jenkins CI will get picked up

**Review by jperez999 — APPROVED** [review]

**Comment by bschifferer** [comment]
rerun tests

**Comment by bschifferer** [comment]
rerun tests

**Comment by bschifferer** [comment]
rerun tests

**Comment by bschifferer** [comment]
rerun tests

**Comment by oliverholworthy** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by oliverholworthy** [comment]
The earlier Jenkins failures were due to the dask version somehow being reverted to an older version.

The tests are now failing due to an AttributeError that may be related to this change.

```
File "/var/jenkins_home/workspace/nvtabular_tests/nvtabular/nvtabular/ops/normalize.py", line 111, in output_dtype

return self.out_dtype or numpy.float64

AttributeError: 'Normalize' object has no attribute 'out_dtype'
```

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
