### PR TITLE
Use merlin-dataloader package

### PR DESCRIPTION
**Pull request by benfred**
Use the merlin-dataloader package under the hood for the nvt dataloader.

### CODE REVIEW

**Review by jperez999 — APPROVED** [review]

**Comment by benfred** [comment]
Current CI failures need a fix included with https://github.com/NVIDIA-Merlin/dataloader/pull/38

**Comment by benfred** [comment]
Rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Comment by benfred** [comment]
rerun tests

**Pull request merged**
