### PR TITLE
Add support for serializing modules involved in LambdaOp execution by value

### PR DESCRIPTION
**Pull request by willb**
These commits address issue #1737 in two ways:

1. by allowing users to direct `Workflow.save` to serialize an explicit list of named modules by value, and
2. by allowing users to direct `Workflow.save` to use a heuristic to automatically infer the external modules involved in a workflow.

Taken together, these commits will make it easier to serialize workflows that are resilient to execution in environments without source files for all of the modules that were available when the workflow was created, e.g., Docker containers.

The main contribution is the addition of a `modules_byvalue` parameter to `Workflow.save`.  If this is passed an explicit list of modules, `Workflow.save` will direct `cloudpickle` to serialize these modules by value.  If it is passed the string `"auto"`, `Workflow.save` will employ a [heuristic approach that will be useful for many real-world uses of LambdaOp](https://github.com/NVIDIA-Merlin/NVTabular/commit/1e82777ba7adf6bec7d5bc59d882d2b258193802).

I believe that it would be harmless and useful to make `"auto"` the default but have not done so in this PR.

For more background on some of the tradeoffs that would be involved in making the heuristic more precise, please see [this blog post](https://chapeau.freevariable.com/2017/12/module-frontier.html). I do not believe that many of the cases I identified in that post (explicit imports within functions, list comprehensions, etc.) are likely to present in realistic NVTabular LambdaOp client code, and thus took a relatively simple approach.

### CODE REVIEW

**Review by karlhigley — APPROVED** [review]

**Comment by karlhigley** [comment]
The CI tests on this PR appear to hang during `test_lambda.py` on GPU, which seems likely to be related to these changes but is somewhat difficult to troubleshoot without an actual error message.

**Comment by willb** [comment]
> The CI tests on this PR appear to hang during `test_lambda.py` on GPU, which seems likely to be related to these changes but is somewhat difficult to troubleshoot without an actual error message.

Thanks, @karlhigley — I’ll try and figure out what’s going on here.

**Comment by willb** [comment]
Thanks, @karlhigley!

**Comment by karlhigley** [comment]
Thank you, @willb! Sorry it took us so long to get it merged, but this looks great. We literally ran into this problem again today, so the timing is fortuitous.

**Pull request merged**
