### PR TITLE
Remove examples Part 1 - Rossmann, RecSys2020, Outbrain

### PR DESCRIPTION
**Pull request by bschifferer**
Hello,

as we discussed a while ago - May - we want to clean up the NVTabular examples. I started with some examples, we do not want to convert and just keep it in previous commits.

Remove:
- Rossmann,
- RecSys2020
- Outbrain

### CODE REVIEW

**Comment by bschifferer** [comment]
@mikemckiernan I updated the README.md in the examples folder. Do I need to change something else related to the documentations, etc.?

**Comment by mikemckiernan** [comment]
@bschifferer , the very last link on this page is broken.  It used to refer to the Outbrain example.  My first instinct is to change it to refer to the Rename operator in the API.

https://nvidia-merlin.github.io/NVTabular/review/pr-1669/resources/architecture.html

I can add a commit or deal with it later.  Please let me know your preference.

**Comment by mikemckiernan** [comment]
> 

Here's my sugg replacement for the last sentence:

```
Refer to the API documentation for the {class}`Rename <nvtabular.ops.Rename>` operator.
```

**Comment by mikemckiernan** [comment]
I found another change to make. In `docs/source/training/tensorflow.rst`, at the very end of the file, I think you/we/I can remove the link to outbrain and leave the movielens one.

**Review by mikemckiernan — APPROVED** [review]
I added some comments on the conversation tab.  Let me know if you'd like me to add a commit.

**Review by benfred — APPROVED** [review]

**Comment by bschifferer** [comment]
@mikemckiernan I updated the two files to fix the broken links - is that correct?

**Comment by mikemckiernan** [comment]
> @mikemckiernan I updated the two files to fix the broken links - is that correct?

Yep, the link looks good--it links into the API reference for `Rename`.

**Review by mikemckiernan — APPROVED** [review]

**Pull request merged**
